name: "Build and Test"

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET 3
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.402
    - name: Setup .NET 2
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.810
    - name: Build
      run: dotnet build -c release
    - name: Test
      run: dotnet test -c release --no-build